version: '3.8'

services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - testcicd_network

  git-server:
    image: gitea/gitea:latest
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./repos:/data
    networks:
      - testcicd_network

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
      args:
        GIT_USER_NAME: "Nicholas Phoon Kai Jin"
        GIT_USER_EMAIL: "2200780@sit.singaporetech.edu.sg"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - testcicd_network

  sonarqube:
    image: sonarqube:lts
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=sonarqube
    networks:
      - testcicd_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: sonarqube
      POSTGRES_PASSWORD: sonarqube
      POSTGRES_DB: sonarqube
    networks:
      - testcicd_network

networks:
  testcicd_network:
    driver: bridge

volumes:
  jenkins_home:
